import express from "express";
import authRoutes from "./Modules/Auth/auth.routes.js";
import adminAuthRoutes from "./Modules/Auth/Adminauth/adminauth.routes.js";
import categoryRoutes from "./Modules/Category/category.routes.js";
import vendorCategoryRoutes from "./Modules/Category/vendorCategory.routes.js";
import productRoutes from "./Modules/Product/product.routes.js";
import vendorProductRoutes from "./Modules/Product/vendorProduct.routes.js";
import variantRoutes from "./Modules/Variant/variant.routes.js";
import vendorVariantRoutes from "./Modules/Variant/vendorVariant.routes.js";
import offerRoutes from "./Modules/Offers/offer.routes.js";
import adminAuditLogRoutes from "./Modules/AdminAuditLog/adminAuditLog.routes.js";
import vendorAuthRoutes from "./Modules/Auth/Vendorauth/vendorauth.routes.js";
import bannerRoutes from "./Modules/Banner/banner.routes.js";
import coupansRoutes from "./Modules/Coupans/coupan.routes.js";
import adminUserRoutes from "./Modules/Users/user.routes.js";
import adminOrderRoutes from "./Modules/Order/adminOrder.routes.js";
import reportsRoutes from "./Modules/Reports/reports.routes.js";
import notificationRoutes from "./Modules/Notifications/notification.routes.js";
import vendorRoutes from "./Modules/Vendors/vendor.routes.js";
import brandRoutes from "./Modules/Brand/brand.routes.js";
import vendorBrandRoutes from "./Modules/Brand/vendorBrand.routes.js";
import dealRoutes from "./Modules/Deals/deal.routes.js";
import homeRoutes from "./Modules/Home/home.routes.js";
import wishlistRoutes from "./Modules/Wishlist/wishlist.routes.js";
import cartRoutes from "./Modules/Cart/cart.routes.js";
import coinRewardRoutes from "./Modules/CoinReward/coinReward.routes.js";
import orderRoutes from "./Modules/Order/order.routes.js";
import supportRoutes from "./Modules/Support/support.routes.js";
import adminSupportRoutes from "./Modules/Support/adminSupport.routes.js";
import reviewRoutes from "./Modules/Reviews/review.routes.js";
import adminReviewRoutes from "./Modules/Reviews/adminReview.routes.js";
import cmsRoutes from "./Modules/CMS/cms.routes.js";
import payoutRoutes from "./Modules/Payouts/payout.routes.js";
import refundRoutes from "./Modules/Refunds/refund.routes.js";
import commissionRoutes from "./Modules/Commissions/commission.routes.js";
import testimonialRoutes from "./Modules/Testimonials/testimonial.routes.js";
import rewardRoutes from "./Modules/Rewards/reward.routes.js";
import adminManagementRoutes from "./Modules/AdminManagement/adminManagement.routes.js";
import returnReasonRoutes from "./Modules/ReturnReasons/returnReason.routes.js";


const router = express.Router();

// set up routes
router.use("/auth", authRoutes);
router.use("/admin", adminAuthRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/vendors", vendorRoutes);
router.use("/admin/orders", adminOrderRoutes);
router.use("/admin/reports", reportsRoutes);
router.use("/admin/coin-reward", coinRewardRoutes);
router.use("/vendor", vendorAuthRoutes);
router.use("/home", homeRoutes);
router.use("/wishlist", wishlistRoutes);
router.use("/cart", cartRoutes);
router.use("/orders", orderRoutes);
router.use("/support", supportRoutes);
router.use("/reviews", reviewRoutes);
router.use("/cms", cmsRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/rewards", rewardRoutes);

// Admin Routes
router.use("/admin/support", adminSupportRoutes);
router.use("/admin/reviews", adminReviewRoutes);
router.use("/admin/cms", cmsRoutes);
router.use("/admin/payouts", payoutRoutes);
router.use("/admin/refunds", refundRoutes);
router.use("/admin/commissions", commissionRoutes);
router.use("/admin/testimonials", testimonialRoutes);
router.use("/admin/rewards", rewardRoutes);
router.use("/admin/management", adminManagementRoutes);
router.use("/vendor/products", vendorProductRoutes);
router.use("/vendor/brands", vendorBrandRoutes);
router.use("/vendor/categories", vendorCategoryRoutes);
router.use("/vendor/variants", vendorVariantRoutes);
router.use("/category", categoryRoutes);

router.use("/products", productRoutes);
router.use("/variants", variantRoutes);
router.use("/offers", offerRoutes);
router.use("/banners", bannerRoutes);
router.use("/admin-audit-logs", adminAuditLogRoutes);
router.use("/coupans", coupansRoutes);
router.use("/notifications", notificationRoutes);
router.use("/brands", brandRoutes);
router.use("/deals", dealRoutes);
router.use("/return-reasons", returnReasonRoutes);
router.use("/admin/return-reasons", returnReasonRoutes);

export default router;
